config/routes.rb
Rails.application.routes.draw do
  # GUEST PAGE
  root "guest#landing"
  get "/", to: "guest#landing", as: :guest_landing_page

  # AUTH USERS
  get "/signin", to: "auth#signin", as: :auth_signin_page
  get "/signup", to: "auth#signup", as: :auth_signup_page
  post "/signup", to: "auth#create", as: :auth_create_user
  post "/login", to: "auth#login", as: :auth_login
  delete "/logout", to: "auth#logout", as: :auth_logout

  # ADMIN USER PAGES
  get "admin/dashboard", as: :admin_dashboard_page
  namespace :admin do
    resources :events do
        collection do
          delete :bulk_delete
      end
    end
    resources :registrations do
      collection do
        delete :bulk_delete
        get :export # Add this line
      end
    end
  end

  # USER PAGES
  get "/dashboard", to: "user#dashboard", as: :user_dashboard_page
  # get "/new", to: "user#new", as: :user_new_events_page
  # post "/new", to: "user#create", as: :user_create_events_page
  resources :events do
    resources :registrations
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
   has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :role, presence: true
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :require_login
  def dashboard
    @events = current_user.events.all
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/dashboard.html.erb
<div class="dashboard-user">
  <div class="user-nav">
    <div class="logo-user">
      <h1>GoEvent</h1>
    </div>
    <div class="logout-user">
      <%= button_to "Logout", auth_logout_path, method: :delete, class: "btn" %>
    </div>
  </div>
  <div class="dashboard-page">
    <div class="event-wrapper">
      <div class="add-events-btn">
        <%= link_to "Create Events", new_event_path %>
      </div>
      <table class="user-events-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Location</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event|%>
            <tr>
              <td><%= event.event_name%></td>
              <td><%= event.date%></td>
              <td><%= event.location%></td>
              <td class="user-events-actions">
                <%= link_to 'View', event_path(event), class: "action-btn" %>
                <%= link_to 'Edit', edit_event_path(event), class: "action-btn" %>
                <%= button_to 'Delete', event_path(event), method: :delete, data: { confirm: 'Are you sure?' }, class: "action-btn action-btn-delete" %>
              </td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>